name: Artifact

on:
  release:
     types: [ prereleased, released ]
     
env:
  BUILD_TYPE: release
  OTHER_PROJECTS: "MulleFoundation/mulle-foundation-developer;
mulle-objc/mulle-objc-developer;
mulle-c/mulle-c-developer;"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
    - name: Add to path
      run:  echo "$HOME/bin" >> $GITHUB_PATH

    - uses: actions/checkout@v3

    - uses: mulle-sde/github-ci@v1

    - uses: mulle-cc/github-ci@v4

    - name: Choose musl on Linux
      run: |
           [ "${{ runner.os }}" != "Linux" ] || mulle-sde env set MULLE_CRAFT_SDKS "musl"

    - name: Mulle-SDE Craft
      run: mulle-sde craft --release

    - name: Get executable
      run: echo "exepath=$(mulle-sde product list)" >> $GITHUB_OUTPUT
      id: executable

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: mulle-markdown.${{ matrix.os }}
        path: ${{ steps.executable.outputs.exepath }}
        retention-days: 1
        
  release:
    needs: [ build ]
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Download linux Artifact
        uses: actions/download-artifact@v3
        with:
          name: mulle-markdown.ubuntu-latest

      - name: Rename linux artifact
        run: |
             # download-artifact@v3 removed extension, thinking it was zip
             mv ${{ github.workspace }}/mulle-markdown ${{ github.workspace }}/mulle-markdown.linux
        
      - name: Download linux Artifact
        uses: actions/download-artifact@v3
        with:
          name: mulle-markdown.macos-latest

      - name: Rename macos artifact
        run: mv ${{ github.workspace }}/mulle-markdown ${{ github.workspace }}/mulle-markdown.macos

      - name: upload artifacts
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          # upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_paths: '[ "mulle-markdown.*" ]'
